version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: '10:00'
    timezone: Europe/London
    day: "friday"
  open-pull-requests-limit: 10
  labels:
      - "dependencies"
  reviewers:
  - warrenbuckley
