version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '10:00'
    timezone: Europe/London
  open-pull-requests-limit: 10
  labels:
      - "npm"
      - "chore"
      - "dependencies"
  reviewers:
  - warrenbuckley
